---
- name: Install EPEL release for nginx
  yum: name=epel-release state=present
 
- name: Install nginx web server
  yum: name=nginx state=installed 
  notify:
     - start nginx

- name: Upload the external conf files
  copy: src={{ item }} dest=/etc/nginx/conf.d/ mode=0644
  with_fileglob:
    - "{{ nginx_conf}}/*"
  notify:
     - start nginx
