---
- hosts: appserver 
  sudo: yes
  gather_facts: False
  vars:
    - app_binary: /var/lib/jenkins/jobs/Testing/lastSuccessful/archive/target/goweb 
    - app_home_dir: /apps/go
    - app_name: goweb
  roles:
    - goweb
