---
- hosts: apps
  sudo: yes
  gather_facts: True
  vars:
    - image_name: pnilesh/centos_sshd
    - num_of_container: 2
    - group_name: app
    - host_name: app
    # Ports wil be itterated starting with range specfied example 900{{item}} will become 9001 and 222{{item}} will become 2221 
    - ports_map: "0.0.0.0:900{{item}}:8484/tcp,0.0.0.0:910{{item}}:22/tcp"
    #Ports expose needs to be  decalred with respect to ports mapped above.
    - ports_expose: "8484,22"
  roles:
    - docker

