---
- hosts: web
  sudo: yes
  gather_facts: True
  vars:
    - image_name: pnilesh/centos_sshd
    - num_of_container: 1
    - group_name: web
    - host_name: web
    # Ports wil be itterated starting with range specfied example 900{{item}} will become 9001 and 222{{item}} will become 2221 
    - ports_map: "0.0.0.0:880{{item}}:80/tcp,0.0.0.0:890{{item}}:22/tcp"
    #Ports expose needs to be  decalred with respect to ports mapped above.
    - ports_expose: "80,22"
  roles:
    - docker

